# This workflow is responsible for building and pushing the Palworld Docker image to the GitHub Container Registry (ghcr.io).
name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Login to ghcr.io
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.4.0
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/palworld:${{ github.sha }},ghcr.io/${{ github.repository }}/palworld:latest
